"""Add timestamp to AnalyzedFile and create RecentActivity

Revision ID: 7da568d165e5
Revises: aa585fc7a0b3
Create Date: 2024-05-22 14:33:06.043728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da568d165e5'
down_revision = 'aa585fc7a0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_files', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
